motor_tables:
  XL430:
    torque_enable: 64
    goal_position: 116
    present_position: 132
    present_current: 126
    present_velocity: 128
    position_bytes: 4
    speed_bytes: 4

  XL320:
    torque_enable: 24
    goal_position: 30
    present_position: 37
    present_current: 38
    present_velocity: 39
    position_bytes: 2
    speed_bytes: 2

robot:
  joints:
    - name: joint_1
      id: 0
      motor_type: XL430
      min: 0
      max: 4095

    - name: joint_2
      id: 1
      motor_type: XL430
      min: 0
      max: 4095

    - name: joint_3
      id: 2
      motor_type: XL430
      min: 0
      max: 4095

    - name: joint_4
      id: 3
      motor_type: XL430
      min: 0
      max: 4095

    - name: joint_5
      id: 4
      motor_type: XL430
      min: 0
      max: 4095

    - name: joint_6
      id: 5
      motor_type: XL430
      min: 0
      max: 4095

    - name: gripper
      id: 6
      motor_type: XL430
      min: 0
      max: 4095

devices:
  dxl_device: "/dev/ttyUSB1"
  rs485_device: "/dev/ttyCH341USB0"

  cameras:
    scene:
      - alias: "scene_camera_bottom"
        device: "/dev/video0"
        width: 1280
        height: 720
      - alias: "scene_camera_top"
        device: "/dev/video6"
        width: 1280
        height: 720
    wrist:
      - alias: "wrist_camera_right"
        device: "/dev/video4"
        width: 2560
        height: 720
